### ISSUE TITLE
CORS origin error

### ISSUE THREAD

**Issue by yanicodeverse** [yanicodeverse/chat-nexus#6]
cors origin error on browsers firefox, brave, chrome

**Comment by rakshyak-98** [comment]
This issue is related to the OS configuration, as sometimes it takes the IP address instead of the hostname.

**Comment by rakshyak-98** [comment]
issue: That is because Node.js 18 and up prefer IPv6 addresses, which means, on many machines, Node.js will resolve localhost to the IPv6 address ::1 and Mongoose will be unable to connect, unless the mongodb instance is running with ipv6 enabled.
[link](https://mongoosejs.com/docs/connections.html)
